/**
 * Move 1, Task C3: anchor distribution across the 116 links this spec placed.
 *
 * Reads the markdown sources rather than a deployment, so it can run before a
 * build. Writes docs/specs/move-1-anchor-distribution.md and exits non-zero if
 * any article carries a number of links other than one, or any anchor is used
 * more than three times in a locale.
 *
 *   node scripts/move-1/anchor-report.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { routes, LOCALES } from './routes-loader.mjs';

const { localizePath } = routes;

const GROUPS = {
  '/wordpress-in-china/': ['baiduspider-firewall', 'china-website-hosting-guide',
    'host-website-in-china', 'great-firewall-what-it-blocks', 'google-analytics-china',
    'china-website-localisation', 'mobile-first-design-china', 'woocommerce-china-store-guide',
    'baidu-structured-data', 'submitting-urls-to-baidu', 'baidu-search-resource-platform',
    'baidu-site-verification', 'baidu-verification-failed', 'baidu-verification-scope',
    'baidu-fast-inclusion-gone', 'china-data-privacy-pipl-dsl'],
  '/wordpress-agency-china/': ['icp-licence-filing-foreign-companies',
    'baidu-seo-ranking-in-china', 'china-content-marketing-strategy',
    'china-search-landscape-beyond-baidu',
    // Task B3: the re-slugged article links to the same service page.
    'vetting-a-wordpress-agency-china'],
  '/web-agency-china/': ['baidu-keyword-research-tools', 'baidu-index-traffic-data',
    'baidu-account-foreign-company', 'baidu-account-ownership', 'baidu-ads-account-foreign',
    'baidu-aicaigou-b2b', 'baidu-merchant-center', 'baidu-product-feed',
    'baidu-product-data-destinations'],
};

const dirFor = (loc) => `src/content/guides${loc === 'en' ? '' : '-' + loc}`;

const problems = [];
const lines = ['# Move 1, anchor distribution', '',
  'Generated by `scripts/move-1/anchor-report.mjs`. One link per article, ' +
  'no anchor repeated more than three times per locale (spec section 4, C3).', ''];

let total = 0;

for (const loc of LOCALES) {
  lines.push(`## ${loc}`, '');
  const anchorCounts = new Map();

  for (const [target, ids] of Object.entries(GROUPS)) {
    const targetPath = localizePath(target, loc);
    lines.push(`### ${targetPath}`, '');
    lines.push('| article | anchor |', '|---|---|');

    for (const id of ids) {
      const file = `${dirFor(loc)}/${id}.md`;
      let md;
      try {
        md = readFileSync(file, 'utf8');
      } catch {
        problems.push(`${loc}: ${file} is missing`);
        continue;
      }
      const body = md.split(/\n---\n/).slice(1).join('\n---\n');
      const found = [...body.matchAll(
        new RegExp(`\\[([^\\]]+)\\]\\(${targetPath.replace(/[/-]/g, '\\$&')}\\)`, 'g'))];

      if (found.length !== 1) {
        problems.push(`${loc}/${id}: ${found.length} links to ${targetPath}, expected 1`);
        continue;
      }
      const anchor = found[0][1];
      anchorCounts.set(anchor, (anchorCounts.get(anchor) || 0) + 1);
      total++;
      lines.push(`| ${id} | ${anchor} |`);
    }
    lines.push('');
  }

  const repeated = [...anchorCounts].filter(([, n]) => n > 3);
  for (const [a, n] of repeated) problems.push(`${loc}: anchor "${a}" used ${n} times, max 3`);

  const maxUse = Math.max(0, ...anchorCounts.values());
  lines.push(`**${anchorCounts.size} distinct anchors across ${[...anchorCounts.values()]
    .reduce((a, b) => a + b, 0)} links. Most-repeated anchor is used ${maxUse} time(s).**`, '');
}

lines.push('---', '', `Total links placed: ${total}.`, '');
writeFileSync('docs/specs/move-1-anchor-distribution.md', lines.join('\n'));

console.log(`anchors: ${total} links recorded, ${problems.length} problems`);
for (const p of problems) console.log(`   - ${p}`);
process.exit(problems.length ? 1 : 0);
